services:
    db:
        image: postgres:15
        container_name: sing-me-a-song-db-e2e
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: singmeasong-e2e
        ports:
            - '5432:5432'
        volumes:
            - db-e2e-data:/var/lib/postgresql/data

    backend:
        build:
            context: ./BACKEND
            dockerfile: Dockerfile.test
        container_name: sing-me-a-song-backend-e2e
        ports:
            - '4000:4000'
        environment:
            DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/singmeasong-e2e?schema=public'
        volumes:
            - ./BACKEND:/app
            - /app/node_modules
        command: sh -c "npm run db && npm run test:e2e"
        depends_on:
            - db

    frontend:
        build:
            context: ./FRONTEND
        container_name: sing-me-a-song-frontend-e2e
        ports:
            - '3000:80'
        depends_on:
            - backend

volumes:
    db-e2e-data:
